Upgrade the packages
wednesday-solutions/react-template pull request #93
Opened 2021-06-24 13:18 UTC by rohansaroha

### Ticket Link
---------------------------------------------------

### Related Links
---------------------------------------------------

### Description
---------------------------------------------------

### Steps to Reproduce / Test
---------------------------------------------------

### GIF's
---------------------------------------------------

2021-06-28 11:38 UTC, rameez-wed requested changes

2021-06-28 11:38 UTC, rameez-wed commented on .storybook/config.js
> +Object.values = (obj) => Object.keys(obj).map((key) => obj[key]);
remove brackets just `obj` should be fine. Same thing for keys

2021-06-28 11:38 UTC, rameez-wed commented on .storybook/config.js
> +const getMessages = (locale) => translationMessages[locale];
remove brackets

2021-06-28 11:38 UTC, rameez-wed commented on babel.config.js
> +        ['import', { libraryName: 'antd', /*  libraryDirectory: 'es', */ style: true }, 'import-antd']
remove if not required

2021-06-28 11:38 UTC, rameez-wed commented on internals/webpack/webpack.config.prod.js
> +        // minifyURLs: true
why is this commented?

2021-07-06 06:24 UTC, christin-wednesday approved these changes

2021-07-06 11:10 UTC, rameez-wed requested changes

2021-07-06 11:10 UTC, rameez-wed commented on app/containers/HomeContainer/index.js
>    useEffect(() => {
remove if unused

2021-07-06 11:10 UTC, rameez-wed commented on .eslintignore.js
> +stats.json.DS_Store;
.DS_Store is a different file.

2021-07-06 11:10 UTC, rameez-wed commented on .eslintignore.js
> +npm - debug.log.idea;
same .idea is a different file.

2021-07-06 11:10 UTC, rameez-wed commented on server/middlewares/frontendMiddleware.js
> +  const isProd = process.env.NODE_ENV === 'production';
semicolons are added everywhere can you remove those?

2021-07-06 13:24 UTC, rameez-wed approved these changes

2021-07-07 08:31 UTC, christin-wednesday requested changes

2021-07-07 08:31 UTC, christin-wednesday commented on server/middlewares/addDevMiddlewares.js
> +  const fs = middleware.fileSystem
```suggestion
   const fs = middleware.context.compiler.outputFileSystem;
```

2021-07-07 10:26 UTC, christin-wednesday approved these changes

2021-07-09 05:28 UTC, merged